### ISSUE TITLE
Build out of memory

### ISSUE THREAD

**Issue by dested** [WonderInventions/node-webrtc#20]
I've tried to build this on a few machines now and they are all doing the same thing. The output below is from wsl2 on windows 11. 

It seems once it gets to the `ninja $TARGETS` step it starts spawning an infinite number of python3 instances, as observed from `top`. I have no idea why or how to start debugging this :-/

Any help would be appreicated!

```
> node scripts/build-from-source.js

Running cmake-js -O build-linux-x64 -a x64
info TOOL Using Unix Makefiles generator.
info CMD CONFIGURE
info RUN [
info RUN   'cmake',
info RUN   '/mnt/c/code/node-webrtc2',
info RUN   '--no-warn-unused-cli',
info RUN   '-G',
info RUN   'Unix Makefiles',
info RUN   '-DCMAKE_JS_VERSION=7.3.0',
info RUN   '-DCMAKE_BUILD_TYPE=Release',
info RUN   '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/mnt/c/code/node-webrtc2/build-linux-x64/Release',
info RUN   '-DCMAKE_MSVC_RUNTIME_LIBRARY=MultiThreaded$<$<CONFIG:Debug>:Debug>',
info RUN   '-DCMAKE_JS_INC=/home/o/.cmake-js/node-x64/v22.5.1/include/node',
info RUN   '-DCMAKE_JS_SRC=',
info RUN   '-DNODE_RUNTIME=node',
info RUN   '-DNODE_RUNTIMEVERSION=22.5.1',
info RUN   '-DNODE_ARCH=x64',
info RUN   '-DCMAKE_JS_LIB=',
info RUN   '-DCMAKE_CXX_FLAGS=-DBUILDING_NODE_EXTENSION'
info RUN ]
Not searching for unused variables given on the command line.
-- The C compiler identification is GNU 11.4.0
-- The CXX compiler identification is GNU 11.4.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Git: /usr/bin/git (found version "2.34.1")
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE
-- Configuring done (2.7s)
-- Generating done (0.1s)
-- Build files have been written to: /mnt/c/code/node-webrtc2/build-linux-x64
Running cmake-js build
info TOOL Using Unix Makefiles generator.
info CMD BUILD
info RUN [
info RUN   'cmake',
info RUN   '--build',
info RUN   '/mnt/c/code/node-webrtc2/build-linux-x64',
info RUN   '--config',
info RUN   'Release'
info RUN ]
[  1%] Creating directories for 'project_depot_tools'
[  2%] Performing download step (git clone) for 'project_depot_tools'
Cloning into 'src'...
HEAD is now at 495b23b3 remove goma CIPD package
[  3%] Performing update step for 'project_depot_tools'
[  4%] No patch step for 'project_depot_tools'
[  5%] No configure step for 'project_depot_tools'
[  6%] No build step for 'project_depot_tools'
[  7%] No install step for 'project_depot_tools'
[  7%] Completed 'project_depot_tools'
[  7%] Built target project_depot_tools
[  8%] Creating directories for 'project_libwebrtc'
[  9%] Performing download step for 'project_libwebrtc'

export PATH=$DEPOT_TOOLS:$PATH

gclient config --unmanaged --spec 'solutions=[{"name":"src","url":"https://webrtc.googlesource.com/src.git"}]'
/mnt/c/code/node-webrtc2/build-linux-x64/external/depot_tools/src/.cipd_bin

gclient sync --shallow --no-history --nohooks --with_branch_heads -r ${WEBRTC_REVISION} -R
Syncing projects:  32% (14/43) src/buildtools/third_party/libc++/trunk
[0:01:43] Still working on:
[0:01:43]   src/third_party

[0:11:13] Still working on:
[0:11:13]   src/third_party
Syncing projects: 100% (43/43), done.

vpython3 src/tools/clang/scripts/update.py
Downloading https://commondatastorage.googleapis.com/chromium-browser-clang/Linux_x64/clang-llvmorg-14-init-11564-g37fbf238-3.tgz .......... Done.

rm -f webrtc

ln -s src webrtc
[ 10%] No update step for 'project_libwebrtc'
[ 11%] No patch step for 'project_libwebrtc'
[ 12%] Performing configure step for 'project_libwebrtc'

export PATH=$DEPOT_TOOLS:${DEPOT_TOOLS}/python-bin:$PATH

cd ${SOURCE_DIR}

case "$(uname -s)" in
  Linux*)
    if [ "$TARGET_ARCH" == "arm" ]; then
      vpython3 build/linux/sysroot_scripts/install-sysroot.py --arch=arm
    elif [ "$TARGET_ARCH" == "arm64" ]; then
      vpython3 build/linux/sysroot_scripts/install-sysroot.py --arch=arm64
    else
      vpython3 build/linux/sysroot_scripts/install-sysroot.py --arch=amd64
    fi
esac
Installing Debian sid amd64 root image: /mnt/c/code/node-webrtc2/build-linux-x64/external/libwebrtc/download/src/build/linux/debian_sid_amd64-sysroot
Downloading https://commondatastorage.googleapis.com/chrome-linux-sysroot/toolchain/95051d95804a77144986255f534acb920cee375b/debian_sid_amd64_sysroot.tar.xz

# NOTE(mroberts): Running hooks generates this file, but running hooks also
# takes too long in CI; so do this manually.
(cd build/util && vpython3 lastchange.py -o LASTCHANGE)

gn gen ${BINARY_DIR} "--args=${GN_GEN_ARGS}"
Done. Made 1086 targets from 261 files in 2676ms
[ 13%] Performing build step for 'project_libwebrtc'

# We want to use system ninja, _NOT_ depot_tools ninja, actually
export PATH="${DEPOT_TOOLS}/python-bin:${PATH}:${DEPOT_TOOLS}"

export TARGETS="webrtc libjingle_peerconnection"
case "$(uname -s)" in
  Darwin*)
  export TARGETS="$TARGETS libc++ libc++abi"
esac

ninja $TARGETS
Python path configuration:
  PYTHONHOME = (not set)
  PYTHONPATH = (not set)
  program name = 'python3'
  isolated = 0
  environment = 1
  user site = 1
  safe_path = 0
  import site = 1
  is in build tree = 0
  stdlib dir = '/mnt/c/code/node-webrtc2/build-linux-x64/external/depot_tools/src/bootstrap-2@3.11.8.chromium.35_bin/python3/lib/python3.11'
  sys._base_executable = '/mnt/c/code/node-webrtc2/build-linux-x64/external/depot_tools/src/bootstrap-2@3.11.8.chromium.35_bin/python3/bin/python3'
  sys.base_prefix = '/mnt/c/code/node-webrtc2/build-linux-x64/external/depot_tools/src/bootstrap-2@3.11.8.chromium.35_bin/python3'
  sys.base_exec_prefix = '/mnt/c/code/node-webrtc2/build-linux-x64/external/depot_tools/src/bootstrap-2@3.11.8.chromium.35_bin/python3'
  sys.platlibdir = 'lib'
  sys.executable = '/mnt/c/code/node-webrtc2/build-linux-x64/external/depot_tools/src/bootstrap-2@3.11.8.chromium.35_bin/python3/bin/python3'
  sys.prefix = '/mnt/c/code/node-webrtc2/build-linux-x64/external/depot_tools/src/bootstrap-2@3.11.8.chromium.35_bin/python3'
  sys.exec_prefix = '/mnt/c/code/node-webrtc2/build-linux-x64/external/depot_tools/src/bootstrap-2@3.11.8.chromium.35_bin/python3'
  sys.path = [
    '/mnt/c/code/node-webrtc2/build-linux-x64/external/depot_tools/src/bootstrap-2@3.11.8.chromium.35_bin/python3/lib/python311.zip',
    '/mnt/c/code/node-webrtc2/build-linux-x64/external/depot_tools/src/bootstrap-2@3.11.8.chromium.35_bin/python3/lib/python3.11',
    '/mnt/c/code/node-webrtc2/build-linux-x64/external/depot_tools/src/bootstrap-2@3.11.8.chromium.35_bin/python3/lib/python3.11/lib-dynload',
  ]
Fatal Python error: init_fs_encoding: failed to get the Python codec of the filesystem encoding
Python runtime state: core initialized
Traceback (most recent call last):
  File "/mnt/c/code/node-webrtc2/build-linux-x64/external/depot_tools/src/bootstrap-2@3.11.8.chromium.35_bin/python3/lib/python3.11/encodings/__init__.py", line 33, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1138, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1078, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1504, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1476, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1616, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1659, in _fill_cache
OSError: [Errno 12] Cannot allocate memory: '/mnt/c/code/node-webrtc2/build-linux-x64/external/depot_tools/src/bootstrap-2@3.11.8.chromium.35_bin/python3/lib/python3.11/encodings'
gmake[2]: *** [CMakeFiles/project_libwebrtc.dir/build.make:86: external/libwebrtc/stamp/project_libwebrtc-build] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:115: CMakeFiles/project_libwebrtc.dir/all] Error 2
gmake: *** [Makefile:91: all] Error 2
ERR! OMG Process terminated: 2
/mnt/c/code/node-webrtc2/scripts/build-from-source.js:41
    throw new Error("cmake-js build failed for wrtc");
    ^

Error: cmake-js build failed for wrtc

Node.js v22.5.1
```

**Comment by hazelduvall** [comment]
Ah yeah I've gotten that a couple times myself. There's a comment from `scripts/build-webrtc.sh` in your output that I think explains what's going wrong:

```bash
# We want to use system ninja, _NOT_ depot_tools ninja, actually
export PATH="${DEPOT_TOOLS}/python-bin:${PATH}:${DEPOT_TOOLS}"
```

The `ninja` executable from depot_tools exhibits this behavior, so I always install it on my system first and have this `PATH` setup to use the system `ninja` instead. I think what's going on is that you don't have `ninja` installed on your system and the build is proceeding with the buggy depot_tools version. Does installing `ninja` on your system fix this for you?

**Comment by dested** [comment]
Yep that was it, thanks!!!
